/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.view.Login', {
    extend: 'Ext.form.Panel',
    alias: 'widget.login',

    requires: [
        'Ext.Container',
        'Ext.Label',
        'Ext.Button'
    ],

    config: {
        scrollable: false,
        items: [
            {
                xtype: 'container',
                padding: '50 0 0 0',
                layout: {
                    type: 'vbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'label',
                        height: 100,
                        html: 'Добро пожаловать в Pixonic Team! Войдите, используя аккаунт @pixonic.ru',
                        id: 'helloLabel',
                        style: 'text-align: center',
                        width: 300
                    },
                    {
                        xtype: 'label',
                        html: '',
                        id: 'loginErrorLabel',
                        padding: '0 0 20 0',
                        style: 'color:red'
                    },
                    {
                        xtype: 'button',
                        action: 'confirm',
                        baseCls: 'google-button-enabled',
                        disabled: false,
                        height: 46,
                        id: 'loginBtn',
                        style: '',
                        width: 191,
                        pressedCls: 'google-button-pressed',
                        text: ''
                    }
                ]
            }
        ]
    }

});