/*
 * File: app/view/PageController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.view.PageController', {
    extend: 'Ext.Container',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.Label'
    ],

    config: {
        items: [
            {
                xtype: 'titlebar',
                centered: false,
                docked: 'top',
                height: 143,
                hidden: false,
                ui: 'light',
                width: 638,
                hideOnMaskTap: false,
                modal: false,
                items: [
                    {
                        xtype: 'button',
                        action: 'menuOpen',
                        baseCls: 'menu-button',
                        height: 51,
                        id: 'menuButton',
                        width: 82,
                        pressedCls: 'menu-button'
                    },
                    {
                        xtype: 'label',
                        baseCls: 'x-title-lable',
                        disabledCls: 'x-title-lable',
                        height: 55,
                        html: 'СОТРУДНИКИ',
                        id: 'title',
                        style: 'text-align: center; color: white; font: bold 40px calibri;',
                        width: 460
                    }
                ]
            }
        ]
    }

});