/*
 * File: app/view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.view.LoginPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginPanel',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Email',
        'Ext.Button',
        'Ext.Label'
    ],

    config: {
        items: [
            {
                xtype: 'fieldset',
                id: 'loginPanel',
                title: 'Welcome to Pixonic Team!',
                items: [
                    {
                        xtype: 'emailfield',
                        id: 'emailField',
                        label: '@pixonic.ru',
                        labelAlign: 'right',
                        labelWidth: '41%',
                        placeHolder: 'email'
                    },
                    {
                        xtype: 'textfield',
                        id: 'passwordField',
                        label: '',
                        name: 'Password',
                        required: true
                    }
                ]
            },
            {
                xtype: 'container',
                height: '100px',
                layout: {
                    type: 'vbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        action: 'confirm',
                        centered: true,
                        id: 'loginBtn',
                        width: '200px',
                        text: 'Login'
                    },
                    {
                        xtype: 'label',
                        cls: 'x-label-error',
                        height: '40 px',
                        html: 'web',
                        id: 'loginErrorLabel'
                    }
                ]
            }
        ]
    }

});