/*
 * File: app/view/PageController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.view.PageController', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.TitleBar',
        'Ext.Label'
    ],

    config: {
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                height: 80,
                itemId: 'mytitlebar',
                ui: 'light',
                items: [
                    {
                        xtype: 'label',
                        height: 42,
                        html: 'СОТРУДНИКИ',
                        id: 'helloLable',
                        style: 'text-align: center',
                        width: 623
                    }
                ]
            }
        ]
    }

});