/*
 * File: app/view/MyNavigationView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.view.MyNavigationView', {
    extend: 'Ext.navigation.View',

    requires: [
        'PixonicTeam.view.LoginPanel',
        'Ext.form.Panel'
    ],

    config: {
        centered: false,
        items: [
            {
                xtype: 'loginPanel',
                title: 'Pixonic Team'
            }
        ]
    }

});