/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PixonicTeam.controller.LoginController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            loginBtn: '#loginBtn',
            errorLabel: '#loginErrorLabel',
            usernameField: '#emailField',
            passwordField: '#passwordField'
        },

        control: {
            "[action=confirm]": {
                tap: 'onButtonTap'
            }
        }
    },

    onButtonTap: function(button, e, eOpts) {
        var me = this;
        var name = me.getUsernameField().getValue();
        var pwd = me.getPasswordField().getValue();

        var usr = Ext.create('PixonicTeam.model.User',{
            email: name + '@pixonic.ru',
            password: pwd,
        });

        var errs = usr.validate();
        var msg = '';

        if (!errs.isValid()) {
            errs.each(function (err) {
                msg += err.getField() + ' : ' + err.getMessage() + '<br/>';
            });
        }

        var errorLbl = me.getErrorLabel();
        errorLbl.setHtml(msg);
        handleAuthClick(e);
    }

});